---
title: BootBlog-2
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Sharad Raj
tagline: A complete jekyll site
description: Lorem ipsum dolor sit amet consectetur, adipisicing elit. 
baseurl: "https://sharadcodes.github.io/bootblog2"
url: "bootblog2"
logo: logo.png

plugins_dir:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jemoji

gems: [jekyll-paginate,jekyll-sitemap,jekyll-feed,jekyll-seo-tag,jemoji]

markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"
author:
  name: Sharad Raj
  description: A passionate <strong>developer and student</strong>
toc:
- title: Home
  url: "/"
- title: Blog
  url: "/blog/"  
- title: Categories
  url: "/categories/"
- title: Projects
  subfolderitems:
  - page: This is a child
    url: https://codingindian.netlify.com
  - page: Another child
    url: https://codingindian.netlify.com
  - page: Edit me in _config.yml
    url: https://www.cwithsharad.cf
